server:
  port: 8090
cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
spring:
  profiles:
    active: local
    include: aws, oauth
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          naver:
            client-id: 6jerkHZoD9RXdOQ4QiPx
            client-secret: MAeZDUomq9
            client-name: Naver
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            clientAuthenticationMethod: post
            authorization-grant-type: authorization_code
            scope:
              - nickname
              - email
              - profile_image
          kakao:
            client-id: b8ee07c1ac7286e9bbf23a58cc2a9717
            client-secret: PWRHV65uFMaE5cqVMsAWFVm8w7rfTeWH
            client-name: Kakao
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url:  jdbc:mysql://database-1.ctoigrkmyecm.ap-northeast-2.rds.amazonaws.com:3306/tripDB
    username: admin
    password: roottrip
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

# cors 설정
cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

jwt:
  secret: 12345678901234567890123456789012

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect
