spring:
  datasource:
    url:  jdbc:mysql://database-1.ctoigrkmyecm.ap-northeast-2.rds.amazonaws.com:3306
    username: admin
    password: roottrip
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true